### ISSUE TITLE
Icon URL in site extension package doesn't work over https

### ISSUE THREAD

**Issue by davidebbo** [reddog-io/RedDog.Search.Portal#8]
https://www.siteextensions.net/packages/search-portal/

The image URL for your package works as http, but fails as https because of invalid cert. Try https://reddog.io/img/reddog-60px.png. Any chance of fixing that? The Azure portal is making changes that causes the icon to be broken in this case.

Thanks!

**Comment by davidebbo** [comment]
@sandrinodimattia just a ping on this one, as the Portal owners are complaining about the broken icon :)

**Comment by sandrinodimattia** [comment]
Hi @davidebbo sorry for the late reply! I've made the icon available through github.io

Can you update the icon to use this url? https://reddog-io.github.io/img/reddog-60px.png

**Comment by davidebbo** [comment]
@sandrinodimattia Thanks! Unfortunately, the way the gallery works, the only way to get it to properly update the image that it shows in the feed is to upload a new version of the package with the URL updated in the .nuspec file. So it's not something I can easily do since I don't have the source package.

You can't reuse the same version, so you can just bump it up from `1.3.1` to `1.3.2`.

**Comment by sandrinodimattia** [comment]
Ok, done! 👍

**Comment by davidebbo** [comment]
Thanks Sandrino! I just checked, and it no longer looks broken in the portal :)

![image](https://cloud.githubusercontent.com/assets/556238/23096885/2757ee1a-f5db-11e6-8d24-3e84301d1f42.png)
